pipeline {
    agent any
     
    stages {
        stage('Building Docker Image') {
            steps {
               sh 'docker build -t bms-server:latest .'
            }
        }
        stage('Delete Previous running Containers') {
            steps {
               sh 'docker rm -f bms-server-prod | echo true'
               sh 'docker system prune --filter=label!=stage=builder -f'
            }
        }
        stage('Running Docker Build on Port 4000') {
            steps {
                sh 'docker run -e ENVIRONMENT=prod -e GS_CERT=true --name bms-server-prod -p 4000:4000 bms-server:latest'
            }
        }
    }
}
