FROM node:12.18.3-alpine as build
WORKDIR /app
COPY package*.json /app/
RUN npm ci
COPY . /app
RUN npm run build-prod
FROM nginx:1.15.8-alpine
COPY default.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist/book-seat /usr/share/nginx/html
COPY ssc/gslab.crt etc/ssl/gslab.crt
COPY ssc/key.key etc/ssl/key.key
EXPOSE 443
EXPOSE 80